/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * telaString.java
 *
 * Created on 06/10/2012, 17:15:43
 */
package pacote;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author marcelotelles
 */
public class telaString extends javax.swing.JInternalFrame {
public static long tempFinal,tempInicial;
public static ArrayList<String> a;

    /** Creates new form telaString */
    public telaString() {
        initComponents();
        a = new ArrayList<String>();
        
    }
     public class teste1 implements Runnable{
        private int i;
        public void run(){
            jProgressBar1.setMinimum(0);
            jProgressBar1.setValue(0);
            
            int fim = Integer.parseInt(txtRegistros1.getText());
            jProgressBar1.setMaximum(fim);
            String conteudo = "";
            for (i=1;i<=fim;i++){
                jProgressBar1.setValue(i);
                jLabel8.setText(jProgressBar1.getValue()+"%");
                conteudo = conteudo + i + "\n";
                conteudo = conteudo + i*10 + "\n";
                //try {
                //    Thread.sleep(100);
                //} catch (InterruptedException ex) {
                //    Logger.getLogger(telaString.class.getName()).log(Level.SEVERE, null, ex);
                //}

            }
            btnFor1.setEnabled(true);
            txtRegistros1.setEnabled(true);
            System.out.println("com string"+conteudo);
            tempFinal = System.currentTimeMillis();
            long dif = (tempFinal - tempInicial);
            //System.out.println("tempInicial"+tempInicial);
            //System.out.println("tempFinal"+tempFinal);
            lblFor1.setText(String.format("%02d min : %02d seg  e %3d ms",((dif/1000)/60), dif/1000, dif%1000));

        }
    }
     public class teste2 implements Runnable{
        private int i;
        public void run(){
            jProgressBar1.setMinimum(0);
            jProgressBar1.setValue(0);
            int fim = Integer.parseInt(txtRegistros2.getText());
            jProgressBar1.setMaximum(fim);
            StringBuilder conteudo = new StringBuilder();
            for (i=1;i<=fim;i++){
                jProgressBar1.setValue(i);
                jLabel8.setText(jProgressBar1.getValue()+"%");
                conteudo.append(i);
                conteudo.append("\n");
                conteudo.append(i*10);
                conteudo.append("\n");
                //try {
                //    Thread.sleep(100);
                //} catch (InterruptedException ex) {
                //    Logger.getLogger(telaString.class.getName()).log(Level.SEVERE, null, ex);
                //}

            }
            btnFor2.setEnabled(true);
            txtRegistros2.setEnabled(true);
            System.out.println("com stringBuilder"+conteudo.toString());
            tempFinal = System.currentTimeMillis();
            long dif = (tempFinal - tempInicial);
            //System.out.println("tempInicial"+tempInicial);
            //System.out.println("tempFinal"+tempFinal);
            lblFor2.setText(String.format("%02d min : %02d seg  e %3d ms",((dif/1000)/60), dif/1000, dif%1000));

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        btnFor2 = new javax.swing.JButton();
        txtRegistros2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFor1 = new javax.swing.JButton();
        txtRegistros1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblFor1 = new javax.swing.JLabel();
        lblFor2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel8.setText("0%");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 125, 140, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setText("0");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 170, 10, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setText("100");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 170, 30, 17);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(170, 110, 260, 40);

        btnFor2.setText("For");
        btnFor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFor2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnFor2);
        btnFor2.setBounds(140, 260, 100, 25);

        txtRegistros2.setText("100");
        getContentPane().add(txtRegistros2);
        txtRegistros2.setBounds(250, 260, 84, 25);

        jLabel1.setText("Registros");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 260, 90, 25);

        jLabel2.setText("String +");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 220, 120, 25);

        jLabel3.setText("StringBuilder");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 260, 120, 25);

        btnFor1.setText("For");
        btnFor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFor1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnFor1);
        btnFor1.setBounds(137, 220, 100, 25);

        txtRegistros1.setText("100");
        getContentPane().add(txtRegistros1);
        txtRegistros1.setBounds(250, 220, 84, 25);

        jLabel4.setText("Registros");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 220, 110, 25);
        getContentPane().add(lblFor1);
        lblFor1.setBounds(420, 220, 300, 25);
        getContentPane().add(lblFor2);
        lblFor2.setBounds(420, 260, 300, 25);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 60, 97, 29);

        setBounds(0, 0, 798, 433);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFor2ActionPerformed
        // TODO add your handling code here:
        tempInicial = System.currentTimeMillis();
        btnFor2.setEnabled(false);
        txtRegistros2.setEnabled(false);
        Runnable r2 = new teste2();
        new Thread(r2).start();
        
    }//GEN-LAST:event_btnFor2ActionPerformed

    private void btnFor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFor1ActionPerformed
        // TODO add your handling code here:
        tempInicial = System.currentTimeMillis();
        btnFor1.setEnabled(false);
        txtRegistros1.setEnabled(false);
        Runnable r1 = new teste1();
        new Thread(r1).start();
    }//GEN-LAST:event_btnFor1ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    a.add("sdfasdfasdfasdsdfasdfasdfasdsdfasdfsdd");
}//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFor1;
    private javax.swing.JButton btnFor2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblFor1;
    private javax.swing.JLabel lblFor2;
    public static javax.swing.JTextField txtRegistros1;
    public static javax.swing.JTextField txtRegistros2;
    // End of variables declaration//GEN-END:variables
}
